CREATE TABLE `user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `full_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Họ tên lấy từ tk google',
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Email lấy từ tk google',
  `phone_number` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Số điện thoại lấy từ tk google',
  `is_mc` bit(1) DEFAULT b'0' COMMENT 'người dùng có phải MC hay ko',
  `age` int DEFAULT NULL COMMENT 'tuổi',
  `nick_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'nghệ danh của MC',
  `credit` decimal(10,2) NOT NULL DEFAULT '0.00' COMMENT 'điểm uy tín của MC',
  `gender` tinyint DEFAULT '0' COMMENT 'giới tính: 0 - chưa set; 1 - nam; 2 - nữ; 3 - khác',
  `is_newbie` bit(1) NOT NULL DEFAULT b'0' COMMENT 'MC có phải MC mới ko',
  `working_area` text COLLATE utf8mb4_unicode_ci COMMENT 'khu vực MC hoạt động',
  `is_verified` bit(1) NOT NULL DEFAULT b'0' COMMENT 'MC đã được xác minh danh tính chưa',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT 'Mô tả về MC',
  `education` text COLLATE utf8mb4_unicode_ci COMMENT 'Học vấn MC',
  `height` decimal(4,1) DEFAULT NULL COMMENT 'chiều cao',
  `weight` decimal(4,1) DEFAULT NULL COMMENT 'cân nặng',
  `avatar_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'link để lấy avatar dịch vụ lưu ảnh',
  `facebook` text COLLATE utf8mb4_unicode_ci COMMENT 'link facebook',
  `zalo` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'số liên hệ zalo',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` int DEFAULT NULL,
  `modified_by` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='người dùng. nếu is_mc=1 thì người dùng vừa là mc, vừa là khách tìm mc, nếu is_mc=0 thì người dùng là khách tìm mc';
